### PR TITLE
Follows PSR-1, 2 & 4 and removes cURL requirement.

### PR DESCRIPTION
**Pull request by Dygear**
I made this pull request to show a version of the example code that follows the PSR standards [1](http://www.php-fig.org/psr/psr-1/), [2](http://www.php-fig.org/psr/psr-2/) and [4](http://www.php-fig.org/psr/psr-4/) as well as removing the cURL requirement. It is made in hopes that it is useful to other people.

### CODE REVIEW

**Comment by jasonjoh** [comment]
Thanks for this. I'll have to go over the changes and figure out how it would impact the tutorial it goes with: https://dev.outlook.com/restapi/tutorial/php.

**Comment by Dygear** [comment]
Ironically the tutorial on that page is the only reason I found this. When I was reading the code I knew some of what was in the examples was not going to work "as is" and would require some programming. I went back up to the top of the page and realized it was on github and pulled that. Once I read the code over and saw that it would work, I started moving away from cURL and moving it towards the PSR standards. I should really put in [PSR-3](http://www.php-fig.org/psr/psr-3/) support in place of the [error_log](http://php.net/manual/en/function.error-log.php) functions. I'd be happy to help with the migration.

**Comment by jasonjoh** [comment]
Merging this into a new branch to make it easier to test and update tutorial steps.

**Comment by jasonjoh** [comment]
Ok, so I've looked this over and I think it's great. However I just don't have time to go through and rewrite the tutorial to match this. I'm also not sold on removing cURL here. cURL seems to be one of the most-used HTTP libs via PHP, so I see value is showing folks how to use it for this :).

So what I will do here is keep the `psr` branch for your version for any folks that want it.

I do want to say thank you for bringing the PSR standards to my attention, I had no idea. I'm pretty much a PHP novice, so this is great. Do you know if there are any good scanner tools that can check PHP code and report on PSR standard violations?

**Comment by Dygear** [comment]
I honestly don't know of any good scanner tools off the top of my head. @nikic does the best PHP Parser that I know of that supports PHP 7.1 that's being released today. [PHP-Parser](https://github.com/nikic/PHP-Parser/releases/tag/v3.0.0) But it doesn't do PSR checks as far as I know.

As far as updating the README.md file for the new code. I'd basically have to rewrite it from scratch. I'm happy to do that, but my English sucks. (I'm a native speaker, and it's my first language, but I still suck at it.) So if you are ok with reading it over, I'm ok with doing the writing.

The reason why I removed cURL was because I run PHP on a production server that doesn't include cURL. I don't have anything against it, I just find that it's not needed to load into memory when I can use the file_get_contents function without an issue so long as the HTTP wrapper is on and functional.

**Pull request merged**
